### PR TITLE
Don't include build files in repo.

### PR DESCRIPTION
**Pull request by avbop**
This looks like a great project! Just so you know, it's customary to not include build files in the repository, and you can tell git to ignore them with the .gitignore file.

### CODE REVIEW

**Comment by innocentop** [comment]
Nice thanks. I think I merged it properly, let me know if there seems to be
a problem still.

**Comment by avbop** [comment]
It looks like the merge worked, but there are still some `.gtex` files in `graduale-tex/` as well as some `.log` and `.pdf` in `Hinkley-drafts/` which I hadn't noticed earlier.

**Comment by innocentop** [comment]
I think I've gotten them.

**Comment by avbop** [comment]
Looks good to me.

**Pull request merged**
